[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.16.0"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/error.html"
  status = 404

# Enable caching but with a less restrictive CSP
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Less restrictive CSP for development
    Content-Security-Policy = "default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval';" 